# Generated by Django 3.2.4 on 2021-08-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Troop',
        ),
    ]
